version: '3.8'
services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - ./shared-config:/app/config
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4000:80"
    volumes:
      - ./frontend:/app
      - ./shared-config:/app/public/config
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  shared-config:

networks:
  app-network:
    driver: bridge
